title: Mario AI Framework
theme: jekyll-theme-cayman
show_downloads: "true"
plugins:
  - jekyll-favicon
favicon: https://raw.githubusercontent.com/amidos2006/Mario-AI-Framework/master/img/favicon.png
